name: ci
on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11.1

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            make install
        - name: Analysing the code with Python linters
          run: |
            make lint
        - name: Run tests
          run: |
            make test-coverage